name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Configure Gradle
        # Initial gradle configuration, install dependencies, etc
        run: ./gradlew help -Dorg.gradle.jvmargs='-Xmx4g -Xms512m' -Dorg.gradle.workers.max=2

      - name: Build project
        run: ./gradlew assemble testDebugUnitTest -Dorg.gradle.jvmargs='-Xmx4g -Xms512m' -Dorg.gradle.workers.max=2 --stacktrace

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: ./app/build/reports

  instrumented-tests:
    needs: build
    runs-on: ubuntu-latest
    if: false

    strategy:
      matrix:
        api-level: [24, 26, 29, 31, 34]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          disable-animations: true
          script: ./gradlew connectedCheck --stacktrace

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: ./app/build/reports
