name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: "-Xmx5120m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: "-Xms1g -Xmx5120m -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process"

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.3
      - name: Install JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Configure Gradle
        # Initial gradle configuration, install dependencies, etc
        run: ./gradlew help
      - name: Build project
        run: ./gradlew assemble testDebugUnitTest --stacktrace
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v2.2.2
        with:
          name: test-reports
          path: ./app/build/reports

  instrumented-tests:
    needs: build
    runs-on: macOS-latest # enables hardware acceleration in the virtual machine
    env:
      JAVA_TOOL_OPTIONS: "-Xmx5120m -Xms1g -XX:+UnlockExperimentalVMOptions"
      GRADLE_OPTS: "-Xms1g -Xmx5120m -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process"
    strategy:
      matrix:
        api-level: [21, 23, 26, 29]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.3
      - name: Install JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2.15.0
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86
          disable-animations: true
          script: ./gradlew connectedCheck --stacktrace
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v2.2.2
        with:
          name: test-reports
          path: ./app/build/reports
